FROM ubuntu:focal

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 TIMEZONE=Asia/Shanghai
ENV PYTHONUNBUFFERED=x

RUN set -eux \
  ; apt-get update -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
      locales tzdata \
      python3 python3-pip python3-setuptools ipython3 \
  ; ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
  ; echo "$TIMEZONE" > /etc/timezone \
  ; sed -i /etc/locale.gen \
		-e 's/# \(en_US.UTF-8 UTF-8\)/\1/' \
		-e 's/# \(zh_CN.UTF-8 UTF-8\)/\1/' \
  ; locale-gen \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN set -eux \
  ; pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \
  ; pip3 --no-cache-dir install ptvsd \
        fastapi uvicorn Requests furl html5lib \
        aiohttp aiohttp-requests \
        PyParsing decorator more-itertools \
        cachetools config pyyaml transitions chronyk fn.py


WORKDIR /app
CMD  ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "3000", "/app/server.py" ]