FROM pybase

ENV websocat_version=1.6.0
ENV just_version=0.8.3
ENV yq_version=3.4.1
ENV wasmtime_version=0.20.0
ENV watchexec_version=1.14.1

ARG websocat_url=https://github.com/vi/websocat/releases/download/v${websocat_version}/websocat_amd64-linux-static
ARG just_url=https://github.com/casey/just/releases/download/v${just_version}/just-v${just_version}-x86_64-unknown-linux-musl.tar.gz
ARG yq_url=https://github.com/mikefarah/yq/releases/download/${yq_version}/yq_linux_amd64
ARG wasmtime_url=https://github.com/bytecodealliance/wasmtime/releases/download/v${wasmtime_version}/wasmtime-v${wasmtime_version}-x86_64-linux.tar.xz
ARG watchexec_url=https://github.com/watchexec/watchexec/releases/download/${watchexec_version}/watchexec-${watchexec_version}-x86_64-unknown-linux-musl.tar.xz

ENV K8S_VERSION=1.19.3
ARG kubectl_url=https://dl.k8s.io/v${K8S_VERSION}/kubernetes-client-linux-amd64.tar.gz
ARG HELM_VERSION=3.4.0
ARG ISTIO_VERSION=1.7.3

RUN set -eux \
  ; apt-get update -y \
  ; DEBIAN_FRONTEND=noninteractive \
    apt-get install -y --no-install-recommends \
        apt-transport-https gnupg-agent software-properties-common lsb-release curl \
  ; curl -s https://packagecloud.io/install/repositories/datawireio/telepresence/script.deb.sh | bash \
  ; apt-get install -y --no-install-recommends \
        ca-certificates pwgen \
        inetutils-ping net-tools iproute2 iptables \
        sudo mlocate procps xz-utils zstd unzip tree \
        curl wget tcpdump socat rsync \
        openssh-client openssh-server gnupg \
        zsh neovim git telepresence \
  #; update-alternatives --set iptables /usr/sbin/iptables-legacy \
  ; sed -i 's/^.*\(%sudo.*\)ALL$/\1NOPASSWD:ALL/g' /etc/sudoers \
  ; sed -i /etc/ssh/sshd_config \
        -e 's!.*\(AuthorizedKeysFile\).*!\1 /etc/authorized_keys/%u!' \
        -e 's!.*\(GatewayPorts\).*!\1 yes!' \
        -e 's!.*\(PasswordAuthentication\).*yes!\1 no!' \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
  ; wget -q -O /usr/local/bin/websocat ${websocat_url} \
    ; chmod a+x /usr/local/bin/websocat \
  ; wget -q -O- ${just_url} \
      | tar zxf - -C /usr/local/bin just \
  ; wget -q -O /usr/local/bin/yq ${yq_url} \
      ; chmod +x /usr/local/bin/yq \
  ; wget -O- ${wasmtime_url} | tar Jxf - --strip-components=1 -C /usr/local/bin \
      wasmtime-v${wasmtime_version}-x86_64-linux/wasmtime \
  ; wget -q -O- ${watchexec_url} \
      | tar Jxf - --strip-components=1 -C /usr/local/bin watchexec-${watchexec_version}-x86_64-unknown-linux-musl/watchexec \
  \
  ; wget -q -O- ${kubectl_url} \
    | tar zxf - --strip-components=3 -C /usr/local/bin kubernetes/client/bin/kubectl \
  ; curl -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin linux-amd64/helm --strip-components=1 \
  ; curl -L https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-linux-amd64.tar.gz \
        | tar zxvf - -C /usr/local/bin istio-${ISTIO_VERSION}/bin/istioctl --strip-components=2



